### ISSUE TITLE
動詞としての「従って」

### ISSUE THREAD

**Issue by tueda** [kn1cht/textlint-rule-preset-ja-engineering-paper#12]
次のテキストのように、動詞として「従って」が使われている場合でも、「したがって」と置き換えるように指摘されます。
```
ここでの記号は慣例に従っている．
```
```
npx textlint --preset preset-ja-engineering-paper --format pretty-error README.md
```
```
✓ ja-engineering-paper/prh: 従って => したがって
/home/tueda/tmp/test-textlint-rule-preset-ja-engineering-paper/README.md:1:11
                            v
    0.
    1. ここでの記号は慣例に従っている．
    2.
                            ^
```

好みにも依るかとは思われますが、参考にしておられる伊藤氏のゼミ資料のように「したがって」と書いた方が読みやすくなるのは接続詞としての用法の場合かと思います。（伊藤氏の資料にも「前例や執筆要項に従って下さい」という動詞としての用法の場合は漢字となっております。）これも改行や句点・ピリオドの直後のみにマッチさせるのはいかがでしょうか？

**Comment by kn1cht** [comment]
ご提案ありがとうございます。 #8 #9 と同様に改行や句点、ピリオド直後のみにマッチするように致します。

**Comment by kn1cht** [comment]
[v1.0.4を公開しました](https://www.npmjs.com/package/textlint-rule-preset-ja-engineering-paper/v/1.0.4)。改善提案ありがとうございました。

**Comment by tueda** [comment]
早速のご対応をありがとうございます。修正されているのを確認いたしました。
