### ISSUE TITLE
文中の「～だから」を「～したがって」とされてしまう

### ISSUE THREAD

**Issue by tueda** [kn1cht/textlint-rule-preset-ja-engineering-paper#8]
次のテキストのように、「だから」が文中にある場合でも、「したがって」に置き換えるよう指摘されます。
```markdown
なぜなら右辺を展開すると恒等的に1だからである．
```

```
npx textlint --preset preset-ja-engineering-paper --format pretty-error README.md
```
```
✓ ja-engineering-paper/prh: だから => したがって
/home/tueda/tmp/test-textlint-rule-preset-ja-engineering-paper/README.md:1:18
                                         v
    0.
    1. なぜなら右辺を展開すると恒等的に1だからである．
    2.
                                         ^
```
また、`textlint --fix`を適用してしまうと、変な日本語（`恒等的に1したがってである`）になります。

**Comment by kn1cht** [comment]
@tueda ご報告、ありがとうございます！　修正します

---

「だから」が「したがって」に置換される理由は、「[リンク：論文に死んでも書いてはいけない言葉３０ - 発声練習](https://next49.hatenadiary.jp/entry/20120103/p2)」で、言い換えるべき口語的な表現として挙がっていることに由来しています。
ご指摘のとおり、文頭以外で使う場合にはこれは的外れな修正です。文頭の「だから」のみがエラーになるよう変更します。

**Comment by kn1cht** [comment]
https://github.com/kn1cht/textlint-rule-preset-ja-engineering-paper/blob/b307a09250a52105d65f7783561d0585db116e3f/src/dict/prh-rules.yml#L57-L65

#9 にて修正完了しました（すぐ下の「でも」「だけど」等と同様に、改行や句点、ピリオド直後のみ反応するようにしました）。

**Comment by kn1cht** [comment]
@tueda [v1.0.3](https://www.npmjs.com/package/textlint-rule-preset-ja-engineering-paper/v/1.0.3) として修正版を公開致しましたので、動作をご確認ください。

**Comment by tueda** [comment]
ご対応ありがとうございます。動作が修正されているのを確認いたしました。
